# Generated by Django 3.2 on 2021-11-19 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_moto', models.CharField(max_length=255)),
                ('shop_bio', models.TextField(blank=True, null=True)),
                ('shop_category', models.CharField(max_length=255)),
                ('phoneNo', models.CharField(max_length=255)),
                ('phoneNo_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_model', models.CharField(blank=True, max_length=255, null=True)),
                ('product_part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('product_price', models.CharField(max_length=255)),
                ('product_promote', models.BooleanField(blank=True, null=True)),
                ('product_promotion', models.CharField(blank=True, max_length=255, null=True)),
                ('product_size', models.CharField(blank=True, max_length=225, null=True)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_creation_date', models.DateField(auto_now_add=True)),
                ('product_specifications', models.TextField(blank=True, null=True)),
                ('product_purchased', models.IntegerField(default=0)),
                ('product_size1', models.CharField(blank=True, max_length=225, null=True)),
                ('product_size2', models.CharField(blank=True, max_length=225, null=True)),
                ('product_size3', models.CharField(blank=True, max_length=225, null=True)),
                ('product_size4', models.CharField(blank=True, max_length=225, null=True)),
                ('product_size5', models.CharField(blank=True, max_length=225, null=True)),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop')),
            ],
        ),
    ]
