# Generated by Django 3.2 on 2021-11-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_size1',
            new_name='product_last_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_purchased',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size5',
        ),
    ]
