# Generated by Django 3.2 on 2021-11-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_checkedout_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedout',
            name='product_creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
