# Generated by Django 3.2 on 2021-11-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_checkedout_product_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedout',
            name='total',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
